/**
 * build-knowledge.ts — compiles src/content/* into one Markdown knowledge
 * string for the chatbot's system prompt (see docs/CHATBOT.md §2, ADR-001 in
 * ARCHITECTURE.md: context-stuffing, not RAG — the corpus is a few thousand
 * tokens so it fits entirely in the prompt).
 *
 * Output is a `.ts` file (not raw `.md`) exporting a string constant, so it
 * can be imported directly by both the Vite frontend build and the Vercel
 * Edge Function bundler for api/chat.ts without needing a raw-text loader.
 *
 * Run via `pnpm build:knowledge` or automatically in `prebuild`.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { content } from "../src/content";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, "../src/content/knowledge.generated.ts");

function formatDate(value: string | "Present"): string {
  return value === "Present" ? "Present" : value;
}

function buildMarkdown(): string {
  const { profile, experience, skills, projects, agenticAI, certifications, links } = content;

  const lines: string[] = [];

  lines.push(`# ${profile.name}`);
  lines.push("");
  lines.push(profile.headline);
  lines.push("");
  lines.push(profile.summary);
  if (profile.location) lines.push(`\nLocation: ${profile.location}`);
  lines.push(`\nDomains worked in: ${profile.domains.join(", ")}`);
  if (profile.stats.length) {
    lines.push("\nKey stats:");
    for (const stat of profile.stats) lines.push(`- ${stat.label}: ${stat.value}`);
  }

  lines.push("\n## Experience");
  for (const job of experience) {
    lines.push(
      `\n### ${job.role} — ${job.company} (${job.domain}) · ${job.start} to ${formatDate(job.end)}`,
    );
    if (job.location) lines.push(`Location: ${job.location}`);
    if (job.summary) lines.push(job.summary);
    for (const highlight of job.highlights) lines.push(`- ${highlight}`);
    if (job.tech.length) lines.push(`Tech used: ${job.tech.join(", ")}`);
  }

  lines.push("\n## Skills");
  for (const cluster of skills) {
    const skillList = cluster.skills
      .map((s) => {
        const parts = [s.name];
        if (s.note) parts.push(`(${s.note})`);
        return parts.join(" ");
      })
      .join(", ");
    lines.push(`\n### ${cluster.category}`);
    lines.push(skillList);
  }

  lines.push("\n## Personal Projects");
  lines.push(
    "Built independently, outside of any employer, as hands-on exploration beyond the day job.",
  );
  for (const project of projects) {
    const statusTags = [
      project.featured && "featured",
      project.inProgress && "in progress",
      project.privateRepo && "private repo — no public link",
    ].filter(Boolean);
    lines.push(`\n### ${project.title}${statusTags.length ? ` (${statusTags.join(", ")})` : ""}`);
    lines.push(project.blurb);
    lines.push(`Tech: ${project.tech.join(", ")}`);
    if (project.domain) lines.push(`Domain: ${project.domain}`);
    const linkParts: string[] = [];
    if (project.links.github) linkParts.push(`GitHub: ${project.links.github}`);
    if (project.links.demo) linkParts.push(`Demo: ${project.links.demo}`);
    if (project.links.tableau) linkParts.push(`Tableau: ${project.links.tableau}`);
    if (project.links.docs) linkParts.push(`Docs: ${project.links.docs}`);
    if (linkParts.length) lines.push(linkParts.join(" · "));
  }

  lines.push("\n## Agentic AI");
  lines.push(agenticAI.intro);
  for (const group of agenticAI.groups) {
    const itemList = group.items
      .map((item) => (item.note ? `${item.name} (${item.note})` : item.name))
      .join(", ");
    lines.push(`\n### ${group.category}`);
    lines.push(itemList);
  }
  if (agenticAI.pursuing) lines.push(`\n${agenticAI.pursuing}`);

  lines.push("\n## Certifications");
  for (const cert of certifications) {
    lines.push(`- ${cert.name} — ${cert.issuer} (${cert.year})`);
  }

  lines.push("\n## Contact & links");
  lines.push(`- LinkedIn: ${links.linkedin}`);
  lines.push(`- GitHub: ${links.github}`);
  lines.push(`- Tableau Public: ${links.tableauPublic}`);
  lines.push(`- Email: ${links.email}`);
  lines.push(`- Résumé PDF: ${profile.resumePdfUrl}`);

  return lines.join("\n").trim() + "\n";
}

function main() {
  const markdown = buildMarkdown();
  const fileContents = `/**
 * knowledge.generated.ts — AUTO-GENERATED by scripts/build-knowledge.ts.
 * Do not hand-edit. Re-run \`pnpm build:knowledge\` after changing anything
 * under src/content/. Consumed by api/_lib/systemPrompt.ts.
 */
export const knowledgeMarkdown = ${JSON.stringify(markdown)};
`;
  writeFileSync(OUT_PATH, fileContents);
  console.log(`[build-knowledge] wrote ${markdown.length} chars to ${OUT_PATH}`);
}

main();
